[package]
name = "slagskip"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
eyre = "0.6.12"
rand = "0.8.5"
ratatui = "0.26.1"
strum = "0.26.2"
strum_macros = "0.26.2"
